INSERT INTO arsenal_match_stats
SELECT match_id,
    home_possession,
    away_possession,
    home_bigChanceCreated,
    away_bigChanceCreated,
    home_totalShots,
    away_totalShots,
    home_shotsOnTarget,
    away_shotsOnTarget,
    home_goalkeeperSaves,
    away_goalkeeperSaves,
    home_passes,
    away_passes,
    home_corners,
    away_corners,
    home_fouls,
    away_fouls,
    home_totalTackles,
    away_totalTackles,
    home_freeKicks,
    away_freeKicks,
    home_yellowCards,
    away_yellowCards,
    home_redCards,
    away_redCards,
    NOW() as updated_at
FROM arsenal_live_match;