INSERT INTO arsenal_match_stats
SELECT match_id,
    home_ballPossession as home_possession,
    away_ballPossession as away_possession,
    home_bigChanceCreated,
    away_bigChanceCreated,
    home_totalShotsOnGoal as home_totalShots,
    away_totalShotsOnGoal as away_totalShots,
    home_shotsOnGoal as home_shotsOnTarget,
    away_shotsOnGoal as away_shotsOnTarget,
    home_goalkeeperSaves,
    away_goalkeeperSaves,
    home_passes,
    away_passes,
    home_cornerKicks as home_corners,
    away_cornerKicks as away_corners,
    home_fouls,
    away_fouls,
    home_totalTackle as home_totalTackles,
    away_totalTackle as away_totalTackles,
    home_freeKicks,
    away_freeKicks,
    home_yellowCards,
    away_yellowCards,
    home_redCards,
    away_redCards,
    NOW() as updated_at
FROM arsenal_live_match;