CREATE TABLE IF NOT EXISTS arsenal_live_match (
    match_id INT,
    status VARCHAR(20),
    start_time BIGINT,
    current_period_start BIGINT,
    home_score INT,
    away_score INT,
    home_ballPossession INT,
    away_ballPossession INT,
    home_bigChanceCreated INT,
    away_bigChanceCreated INT,
    home_totalShotsOnGoal INT,
    away_totalShotsOnGoal INT,
    home_shotsOnGoal INT,
    away_shotsOnGoal INT,
    home_goalkeeperSaves INT,
    away_goalkeeperSaves INT,
    home_passes INT,
    away_passes INT,
    home_cornerKicks INT,
    away_cornerKicks INT,
    home_fouls INT,
    away_fouls INT,
    home_totalTackle INT,
    away_totalTackle INT,
    home_freeKicks INT,
    away_freeKicks INT,
    home_yellowCards INT,
    away_yellowCards INT,
    home_redCards INT,
    away_redCards INT,
    proctime AS PROCTIME()
) WITH(
    'connector' = 'kafka',
    'topic' = 'arsenal_live_match',
    'properties.bootstrap.servers' = 'kafka:9092',
    'properties.group.id' = 'arsenal-flink-group',
    'format' = 'json',
    'scan.startup.mode' = 'latest-offset',
    'json.ignore-parse-errors' = 'true'
);