CREATE TABLE IF NOT EXISTS arsenal_live_match (
    match_id INT,
    home_possession INT,
    away_possession INT,
    home_bigChanceCreated INT,
    away_bigChanceCreated INT,
    home_totalShots INT,
    away_totalShots INT,
    home_shotsOnTarget INT,
    away_shotsOnTarget INT,
    home_goalkeeperSaves INT,
    away_goalkeeperSaves INT,
    home_passes INT,
    away_passes INT,
    home_corners INT,
    away_corners INT,
    home_fouls INT,
    away_fouls INT,
    home_totalTackles INT,
    away_totalTackles INT,
    home_freeKicks INT,
    away_freeKicks INT,
    home_yellowCards INT,
    away_yellowCards INT,
    home_redCards INT,
    away_redCards INT,
    proctime AS PROCTIME(),
    PRIMARY KEY (match_id) NOT ENFORCED
) WITH(
    'connector' = 'kafka',
    'topic' = 'arsenal_live_match',
    'properties.bootstrap.servers' = 'kafka:9092',
    'properties.group.id' = 'arsenal-flink-group',
    'format' = 'json',
    'scan.startup.mode' = 'latest-offset',
    'json.ignore-parse-errors' = 'true'
);